package mssql

const (
	serverProp               = "server"
	databaseProp             = "database"
	principalIdProp          = "principal_id"
	usernameProp             = "username"
	objectIdProp             = "object_id"
	passwordProp             = "password"
	sidStrProp               = "sid"
	clientIdProp             = "client_id"
	authenticationTypeProp   = "authentication_type"
	defaultSchemaProp        = "default_schema"
	defaultDboPropDefault    = "dbo"
	rolesProp                = "roles"
	loginNameProp            = "login_name"
	permissionsProp          = "permissions"
	roleNameProp             = "role_name"
	schemaNameProp           = "schema_name"
	ownerNameProp            = "owner_name"
	ownerIdProp              = "owning_principal_id"
	schemaIdProp             = "schema_id"
	typeStrProp              = "type"
	defaultDatabaseProp      = "default_database"
	defaultDatabaseDefault   = "master"
	defaultLanguageProp      = "default_language"
	datasourcenameProp       = "data_source_name"
	datasourceIdProp         = "data_source_id"
	locationProp             = "location"
	rdatabasenameProp        = "remote_database_name"
	credentialNameProp       = "credential_name"
	identitynameProp         = "identity_name"
	secretProp               = "secret"
	credentialIdProp         = "credential_id"
	sqlscriptProp            = "sqlscript"
	verifyObjectProp         = "verify_object"
	keynameProp              = "key_name"
	keyguidProp              = "key_guid"
	symmetrickeyidProp       = "symmetric_key_id"
	keylengthProp            = "key_length"
	keyalgorithmProp         = "key_algorithm"
	algorithmdescProp        = "algorithm_desc"
)
