name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - uses: pre-commit/action@v3.0.1

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          cache: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

  test:
    runs-on: ubuntu-latest
    needs: [pre-commit, security]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_wrapper: false

    - name: Run unit tests
      run: make test

    - name: Run acceptance tests
      run: |
        make docker-start
        sleep 30
        make testacc-local
        make docker-stop
